### PR TITLE
Implement find free time slots command 

### PR DESCRIPTION
**Pull request by Kenlhc**
Feel free to point out any areas of improvement! I will work on them as soon as possible. Thank You.

### CODE REVIEW

**Comment by jasperosy** [comment]
Good job on slapping hard. However, there are some magic numbers that need to be rectified based on jinyao's standard. The linesplit integers for indexing need to be replaced by constants. The same applies for your boolean function if possible. In my opinion, its good to replace stop with a more meaningful time like endDate or endTiming.

**Comment by Kenlhc** [comment]
Thanks for pointing it out. I will rectify these issues soon.

**Comment by kahlokkee** [comment]
Consider placing generic utility methods like convertDateToString and convertStringtoDate under the parent Command class such that other command classes that we implement in the future can inherit and use them.

Also for the constant variables, it could be better named (especially for conversion), HOUR could be renamed to MILLISECONDS_TO_HOURS and TWENTY_FOUR_HOURS could be renamed to UPCOMING_THRESHOLD or something similar such that if we were to change the number of hours for a deadline to be considered upcoming, we would not have to change the constant name.

**Comment by Kenlhc** [comment]
Made changes according to the comments made. Do let me know if there are any other areas for me to work on.

**Pull request merged**
