### PR TITLE
Implement Productivity Tracker and refactor Help, Schedule and Summary Command.

### PR DESCRIPTION
**Pull request by debbiextan**
Feel free to comment. More commits to come for this PR.

Minor changes made to Task class.

### CODE REVIEW

**Comment by jasperosy** [comment]
Check your changes, I believe you made changes to CommandParser and that led to the merging of imports for commands. Change them to single line imports. Missing javadoc for certain Ui methods.

**Comment by debbiextan** [comment]
Thanks for pointing that out. Travis errors are now fixed!

**Review by kahlokkee — CHANGES_REQUESTED** [review]
Resolve the merge conflicts

**Comment by debbiextan** [comment]
Merge conflicts resolved and ready for review and merging, @KahLokKee.

**Review by kahlokkee — APPROVED** [review]

**Pull request merged**
