### PR TITLE
Implement PauseTracker Command

### PR DESCRIPTION
**Pull request by debbiextan**
Please take note and check through the fixed made towards access modifier related Warnings in our Ui class.

### CODE REVIEW

**Comment by kahlokkee** [comment]
Don't anyhow change the access modifiers, also your fork is outdated.

**Comment by Kenlhc** [comment]
Do update your fork. At the same time, java docs are not required for the isExit method.

**Comment by debbiextan** [comment]
Merge conflicts from previous PR fixed. New Travis errors and JavaDocs changes will do tonight.

**Review by jasperosy — CHANGES_REQUESTED** [review]
There are multiple syntax errors in your code, please correct them before making a pull request. If your pull request isnt meant for code that is to be pushed for midv1.3, please close the PR and only create it after submission time. Try not to leave a hanging PR like this

**Comment by debbiextan** [comment]
Noted.

**Pull request closed without merging**
