### PR TITLE
Implement Help Command and other minor edits to UG and Schedule Command.

### PR DESCRIPTION
**Pull request by debbiextan**

### CODE REVIEW

**Comment by kahlokkee** [comment]
Is there a need to throw IOException from Ui to HelpCommand to Oof? Such a low level exception should be handled locally using try catch. Also, why is IOException typecasted to OofException when they are separate classes? Also, calling IOException.getMessage() (from .printOofException()) will return a null pointer (potentially causing a NullPointerException if not handled properly). 

Expect more attention to detail to be placed on such issues and code quality matters in the future.

**Comment by debbiextan** [comment]
Thank you for your feedback @KahLokKee .

IOException is a requirement for the use of Java.io related libraries (in this case, File, FileReader and BufferedReader) to showcase the .txt file related to our Help command. On top of that, in order to have all System.out statements in Ui, it is required that we import IOException into the execute method for Command as well. Typecasting of IOException to OofException is required for Oof to run exception messages correctly. Please suggest if there is a better way to handle this that I may have overlooked. Thanks!

**Comment by kahlokkee** [comment]
Please read my comment again.... I am questioning your choice of implementation, not asking you how it works. I understand well enough how IOExceptions work and how where & when its used. 

As I have already said you should not be throwing IOException from Ui to HelpCommand to Oof when it is entirely possible to catch IOException in the method under Ui and handle it accordingly without throwing it to the caller. (What you are doing is also super redundant, throwing IOException from Ui to HelpCommand to Oof which in turn calls a method from the Ui class).

And no, typecasting IOException to OofException is a very dangerous way of handling the exception because they are not related to each other (since OofException is not a subclass of IOException and vice versa)

**Comment by jasperosy** [comment]
My opinion is in line with @KahLokKee. Try to not change the method signature for parent classes as they may bring about unforeseen bugs especially when we are performing regressional testing. Notice we tried to keep implementations within our child classes by catching the specific exception and then throwing OofExceptions. Maybe you can start from there as the parent command class cannot be weirdly throwing our custom OoofException and a very specific exception.

**Comment by debbiextan** [comment]
I will relook and try to find a better approach if possible to contain the Help command implementations within my child command class. Thanks.

**Comment by debbiextan** [comment]
Updates for Help command has been made. It is now ready for peer review and merges.

**Pull request merged**
